<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // ✅ Add this line


class CompaniesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void{
        //
        $companies = [
            "800 Tek FACILITIES MANAGEMENT L.L.C",
            "A A S A MIDDLE EAST CONTRCTING Co L.L.C",
            "A AND K FIRE AND SAFETY EQUIPMENT L.L.C",
            "ADVANCE APEX BUILDING SOLUTIONS L.L.C",
            "AEON GENERAL CONTRACTING SOLE PROPRIETORSHIP L.L.C",
            "AGILE ADVANCE TECHNICAL SERVICES L.L.C",
            "AIR KING TECHNICAL SERVICES L.L.C",
            "AL BAHER ALGHAREEB TECHNICAL SERVICES L.L.C",
            "AL FAHIDI GASTECH L.L.C",
            "AL MEAMAR RENTAL L.L.C",
            "AL TELAL CONTRACTING AND GENERAL MAINTENANCE L.L.C",
            "ALLIED DCI BUILDING CONTRACTING L.L.C",
            "AMPEON ELECTROMECHANICAL WORKS L.L.C",
            "ASIA EXPRESS TRANSPORT AND GENERAL CONTRACTING L.L.C",
            "AXON SIGNAGE INDUSTRIES L.L.C",
            "BAGORIYA STAR L.L.C",
            "BOND METAL FABRICATION L.L.C",
            "BROTHERS HAEVY EQUIPMENT RENTAL L.L.C",
            "CITY CONSTRUCTION GENERAL CONTRACTING L.L.C",
            "COOL BOSS HVAC TECHNICAL SERVICES L.L.C",
            "CORODEX INDUSTRIES L.L.C",
            "DELTA AL EMARATE BULIDING CONTRACTING L.L.C",
            "DUTCH FOUNDATION COMPANY W.L.L",
            "EAST GATE BLACKSMITH WELDING L.L.C",
            "ECO SENSE CONTRACTING L.L.C",
            "ECRODRILL TECHNICAL SERVICES L.L.C",
            "EMIRATE EUROPE FAST BULIDING TECH. SYSTEM",
            "ESHAAL FIRE MAINTENANCE AND GENERAL CONTRACTING L.L.C",
            "EXCEL KITCHEN L.L.C",
            "FABCON GENEREAL CONTRACTING L.L.C",
            "FAST TO FAST INFORMATION TECHNOLOGY CO.L.L.C",
            "FIREWAY GENERAL MAINTENANCE - SOLE PROPRIETORSHIP LLC",
            "FLOOR CIRCLE TECHNICAL SERVICES EST.",
            "FOURTH DIMENSION PIPELINE SERVICES LLC",
            "FREE BIRD GENERAL MAINTENANCE L.L.C",
            "GHASEELCO BULIDING CLEANING - SOLE PROPRIETORSHIP LLC",
            "GLOBAL ALARMS SAFETY & SECURITY EQUIPMENT L.L.C",
            "GLODEN FLAG",
            "GREEN LANTERN FOR GENERAL MAINTENANCE AND CONTRACTING L.L.C",
            "HAMDAN BUILDING CLEANING SERVICES L.L.C",
            "IMPERIAL ELECTROMECHANICAL L.L.C",
            "INDUS PROFESSIONAL ELECTROMECHANICAL CONTRACTING L.L.C",
            "KALFAN ALBADWAWI EQUIPMENT RENTAL L.L.C",
            "KHYBER LAND TRANSPORT BY HEAVY AND LIGHT TRUCKS L.L.C",
            "KIFAZIZ ALBLOSHI FOR LANDSCAPE & GARDENING WORKS & MAINTENANCE CO. L.L.C",
            "LILIES 1 STOP FACILITY SERVICES",
            "MAPCO BUILDINGS MAINTENANCE - L.L.C - O.P.C",
            "MASTER BREEZE TECHNICAL SERVICES L.L.C",
            "MASTER CARE GENERAL MAINTENANCE SOLE PROPRIETORSHIP LLC",
            "MOHAMMED SADIQ CENTRAL AIR CONDITIONER WORKS L.L.C",
            "NATIONAL MARINE DREDGING COMPANY (NMDC)",
            "NOVA SYSTEMS ENGINEERING - SOLE PROPRIETORSHIP L. L. C",
            "PETRO TECHNIC GENERAL CONTRCTING L L C",
            "PRO ELITE MIDDLE GENERAL MAINTENANCE - L.L.C - O.P.C",
            "RANJANA GENERAL CONTRACTING -L.L.C-OPC",
            "REAL ESTATE INVESTMENT & SERVICES COMPANY L.L.C",
            "RED SEA EAGLE ELECTROMECHANICAL CONTRACING L.L.C",
            "REEM ALBARARI ELECTROMECHANICAL EQUIPMENT INSTALLATION & MAINTENANCE",
            "RIGHT TO RIGHT TECHNICAL SERVICES EST",
            "RING ROAD TRANSPORT - SOLE PROPRIETORSHIP L.L.C",
            "ROYAL CROWN GENERAL CONTRACTING SOLE-PROPERITORSHIP L.L.C",
            "SABHA ADVERTISING COMPANY L.L.C",
            "SEVENTY TWO STAR TRANSPORT SOLE -PROPERITORSHIP L.L.C",
            "SHAMS AL MADINA METALCOATING L.L.C",
            "SIGMA INTEGRATED TECHNICAL SERVICES L.L.C",
            "SKY VISION AIR CONDITIONER MAINTENANCE L.L.C-O.P.C",
            "SMOOTH MANPOWER SUPPLE SERVICES L.L.C",
            "STAR ROSE CONSTRUCTION & ELECTROMECHANICAL -SOLE PROPRITEORSHIP L.L.C",
            "SUN & SKY ELETROMECHANICAL AND GENERAL CONTRACTING L L C",
            "TARIQ AL KHOOR BULIDINGS MAINTENANCE L.L.C",
            "TATWEER MIDDLE EAST AND AFRICA L.L.C",
            "THE GOLDEN CROWN DÉCOR CO",
            "THIRD PARTY SAFETY CONSULTANCY",
            "TORNADO GENERAL CONTRACTING",
            "TRADEX ENGINEERING INDUSTRIES LLC",
            "TRIO EXPERTS TECHINICAL SERVICES CO L.L.C",
            "UNITED ENIGINEERING CONSTRUCTION CO (L.L.C)",
            "VORTEX HYDROMECH - L.L.C - O.P.C",
            "WESTCALL",
            "YOUSIF BAQRAIN BUILDING CONTRACTING LLC",
            "ZM DELIVERY SERVICES CO.",
        ];

        foreach ($companies as $company) {
            // Only insert if not already in DB
            if (!DB::table('companies')->where('name', $company)->exists()) {
                DB::table('companies')->insert([
                    'name' => $company,
                    'status' => 'active',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
